### PR TITLE
Create a refresher class to hold open the session

### PR DESCRIPTION
**Pull request by maresb**
This is necessary for my own sanity while experimenting.

This could also be useful in case we need to perform an operation that takes longer than the 5 minute timeout.

### CODE REVIEW

**Comment by grindsa** [comment]
Hi, thanks for submitting this PR. Let me have a deeper look in the upcoming days.  
I btw. skipped the implementation of a refresh-intervall in past on purpose as i could not imagine use-cases requiring it.

**Comment by maresb** [comment]
Thanks a lot for your consideration, and for maintaining this project!

I'm really curious how you debug the code. Do you constantly reauthorize yourself each time you make a change? That would drive me crazy.

I use a notebook with the autoreload feature enabled so that I can interactively explore the API. Once I built and started the refreshers I no longer got disconnected. I was even still connected after cooking and eating dinner, so I'm fairly confident that the code works well.

Since this uses a daemon thread, it won't block the `python` process from terminating.

If you have reservations, there are a lot of potential compromises. We could make it disabled by default. If you simply don't want to deal with it, then I can just keep it on my dev branch and invoke it manually.

**Comment by maresb** [comment]
Rebased the same 4 commits on `devel` with no changes.

I see the tests are now running and failing. I'll try to take a look at that soon.

**Comment by grindsa** [comment]
Hi,

I am debugging the code by l constant reauthorization, but this does not disturb me that much. But you are right, a refresher makes sende for development purposes.  Further do also see some value when using the CLI.

Can we make it configurable?

/G

**Comment by maresb** [comment]
@grindsa, ready for review

**Comment by maresb** [comment]
They changed the refresh logic and now it's broken. :cry:

**Comment by grindsa** [comment]
thank you very much. Let me have a deeper look.

**Pull request merged**
